export const localTestSubmissions = [
  {
    id: "local-booking-1",
    intent: "booking",
    name: "Sofie Hansen",
    email: "sofie@example.com",
    phone: "+45 22 33 44 55",
    country: "DK",
    stayPurpose:
      "Family holiday close to the beach with grandparents joining for part of the stay.",
    guests: { adults: 3, children: 2, babies: 0, total: 5 },
    selection: {
      start: "2026-08-12",
      endExclusive: "2026-08-19",
      nights: 7,
      totalAfterAirbnbDiscountDKK: 21750,
      totalWithCleaningDKK: 24304,
      airbnbServiceFeeSavingsDKK: 2554,
    },
    message: "We would love to hear more about linen and child-friendly extras.",
    status: "sent",
    createdAtMs: Date.UTC(2026, 5, 26, 9, 10),
  },
  {
    id: "local-contact-1",
    intent: "inquiry",
    name: "Sofie Hansen",
    email: "sofie@example.com",
    country: "DK",
    message: "Just checking whether early arrival is ever possible on request.",
    status: "sent",
    createdAtMs: Date.UTC(2026, 5, 26, 8, 55),
  },
  {
    id: "local-extra-1",
    intent: "extra-services",
    name: "Mikkel Larsen",
    email: "mikkel@example.com",
    country: "DK",
    extras: {
      stayDate: "2026-08-12",
      totalDKK: 1495,
      items: [
        {
          id: "linen-pack",
          qty: 5,
          unitPriceDKK: 199,
          label: { en: "Linen package" },
        },
        {
          id: "crib",
          qty: 1,
          unitPriceDKK: 500,
          label: { en: "Baby crib" },
        },
      ],
    },
    status: "mail_failed",
    mailError: "SMTP timeout while notifying admin.",
    createdAtMs: Date.UTC(2026, 5, 26, 8, 40),
  },
  {
    id: "local-checkin-1",
    intent: "guest-checkin",
    name: "Sofie Hansen",
    email: "sofie@example.com",
    checkin: {
      type: "checkin",
      typeLabel: "Check-in",
      keycode: "6142",
      meterReadings: {
        electricity: "19402",
        waterHouse: "982",
        waterPool: "411",
      },
      attachments: [
        {
          filename: "front-door.jpg",
          contentType: "image/jpeg",
          sizeBytes: 214000,
        },
      ],
    },
    status: "sent",
    createdAtMs: Date.UTC(2026, 5, 26, 8, 25),
  },
  {
    id: "local-checkout-1",
    intent: "guest-checkin",
    name: "Mikkel Larsen",
    email: "mikkel@example.com",
    checkin: {
      type: "checkout",
      typeLabel: "Check-out",
      meterReadings: {
        electricity: "19610",
        waterHouse: "1013",
        waterPool: "430",
      },
    },
    message: "We left the key in the lockbox and started the dishwasher.",
    status: "pending",
    createdAtMs: Date.UTC(2026, 5, 26, 7, 50),
  },
] as const;
